'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace RegSrv
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RegSrv.eperHelperRegWS_if")>  _
    Friend Interface eperHelperRegWS_if
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/RegisterCode", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/RegisterCodeResponse")>  _
        Function RegisterCode(ByVal Code As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/UploadRegBak", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/UploadRegBakResponse")>  _
        Function UploadRegBak(ByVal Token As String, ByVal Code As String, ByVal ServerRegXmlZipped() As Byte) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/DownloadRegBak", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/DownloadRegBakResponse")>  _
        Function DownloadRegBak(ByVal Token As String, ByVal Code As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/InvalidateCodebyCode", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/InvalidateCodebyCodeResponse")>  _
        Function InvalidateCodebyCode(ByVal Token As String, ByVal Code As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/CheckCodeUsable", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/CheckCodeUsableResponse")>  _
        Function CheckCodeUsable(ByVal Token As String, ByVal Code As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/StatusCheck", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/StatusCheckResponse")>  _
        Function StatusCheck(ByVal Token As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/DumpFullDT", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/DumpFullDTResponse")>  _
        Function DumpFullDT(ByVal Token As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/UploadNewCode", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/UploadNewCodeResponse")>  _
        Function UploadNewCode(ByVal Token As String, ByVal CodeList() As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/ListRegsInPeriod", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/ListRegsInPeriodResponse")>  _
        Function ListRegsInPeriod(ByVal Token As String, ByVal StartDate As Date, ByVal EndDate As Date) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/DeletebyId", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/DeletebyIdResponse")>  _
        Function DeletebyId(ByVal Token As String, ByVal IdToDelete As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/SetOtherState", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/SetOtherStateResponse")>  _
        Function SetOtherState(ByVal Token As String, ByVal IdToChange As Integer, ByVal Operation As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eperHelperRegWS_if/SetRegDate", ReplyAction:="http://tempuri.org/eperHelperRegWS_if/SetRegDateResponse")>  _
        Function SetRegDate(ByVal Token As String, ByVal IdToChange As Integer, ByVal WhenRegistered As Date) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface eperHelperRegWS_ifChannel
        Inherits RegSrv.eperHelperRegWS_if, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class eperHelperRegWS_ifClient
        Inherits System.ServiceModel.ClientBase(Of RegSrv.eperHelperRegWS_if)
        Implements RegSrv.eperHelperRegWS_if
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RegisterCode(ByVal Code As String) As String Implements RegSrv.eperHelperRegWS_if.RegisterCode
            Return MyBase.Channel.RegisterCode(Code)
        End Function
        
        Public Function UploadRegBak(ByVal Token As String, ByVal Code As String, ByVal ServerRegXmlZipped() As Byte) As String Implements RegSrv.eperHelperRegWS_if.UploadRegBak
            Return MyBase.Channel.UploadRegBak(Token, Code, ServerRegXmlZipped)
        End Function
        
        Public Function DownloadRegBak(ByVal Token As String, ByVal Code As String) As Byte() Implements RegSrv.eperHelperRegWS_if.DownloadRegBak
            Return MyBase.Channel.DownloadRegBak(Token, Code)
        End Function
        
        Public Function InvalidateCodebyCode(ByVal Token As String, ByVal Code As String) As String Implements RegSrv.eperHelperRegWS_if.InvalidateCodebyCode
            Return MyBase.Channel.InvalidateCodebyCode(Token, Code)
        End Function
        
        Public Function CheckCodeUsable(ByVal Token As String, ByVal Code As String) As String Implements RegSrv.eperHelperRegWS_if.CheckCodeUsable
            Return MyBase.Channel.CheckCodeUsable(Token, Code)
        End Function
        
        Public Function StatusCheck(ByVal Token As String) As String Implements RegSrv.eperHelperRegWS_if.StatusCheck
            Return MyBase.Channel.StatusCheck(Token)
        End Function
        
        Public Function DumpFullDT(ByVal Token As String) As String Implements RegSrv.eperHelperRegWS_if.DumpFullDT
            Return MyBase.Channel.DumpFullDT(Token)
        End Function
        
        Public Function UploadNewCode(ByVal Token As String, ByVal CodeList() As String) As String Implements RegSrv.eperHelperRegWS_if.UploadNewCode
            Return MyBase.Channel.UploadNewCode(Token, CodeList)
        End Function
        
        Public Function ListRegsInPeriod(ByVal Token As String, ByVal StartDate As Date, ByVal EndDate As Date) As String Implements RegSrv.eperHelperRegWS_if.ListRegsInPeriod
            Return MyBase.Channel.ListRegsInPeriod(Token, StartDate, EndDate)
        End Function
        
        Public Function DeletebyId(ByVal Token As String, ByVal IdToDelete As Integer) As Boolean Implements RegSrv.eperHelperRegWS_if.DeletebyId
            Return MyBase.Channel.DeletebyId(Token, IdToDelete)
        End Function
        
        Public Function SetOtherState(ByVal Token As String, ByVal IdToChange As Integer, ByVal Operation As Integer) As Boolean Implements RegSrv.eperHelperRegWS_if.SetOtherState
            Return MyBase.Channel.SetOtherState(Token, IdToChange, Operation)
        End Function
        
        Public Function SetRegDate(ByVal Token As String, ByVal IdToChange As Integer, ByVal WhenRegistered As Date) As Boolean Implements RegSrv.eperHelperRegWS_if.SetRegDate
            Return MyBase.Channel.SetRegDate(Token, IdToChange, WhenRegistered)
        End Function
    End Class
End Namespace
