'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKmentes() As String
            Get
                Return CType(Me("mappaANYKmentes"),String)
            End Get
            Set
                Me("mappaANYKmentes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKfuttatas() As String
            Get
                Return CType(Me("mappaANYKfuttatas"),String)
            End Get
            Set
                Me("mappaANYKfuttatas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TSACertDefault() As String
            Get
                Return CType(Me("TSACertDefault"),String)
            End Get
            Set
                Me("TSACertDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SignCertDefault() As String
            Get
                Return CType(Me("SignCertDefault"),String)
            End Get
            Set
                Me("SignCertDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OCSPCertDefault() As String
            Get
                Return CType(Me("OCSPCertDefault"),String)
            End Get
            Set
                Me("OCSPCertDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TSURL() As String
            Get
                Return CType(Me("TSURL"),String)
            End Get
            Set
                Me("TSURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TSUN() As String
            Get
                Return CType(Me("TSUN"),String)
            End Get
            Set
                Me("TSUN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TSPW() As String
            Get
                Return CType(Me("TSPW"),String)
            End Get
            Set
                Me("TSPW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HKPUName() As String
            Get
                Return CType(Me("HKPUName"),String)
            End Get
            Set
                Me("HKPUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PKPUName() As String
            Get
                Return CType(Me("PKPUName"),String)
            End Get
            Set
                Me("PKPUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UKPUName() As String
            Get
                Return CType(Me("UKPUName"),String)
            End Get
            Set
                Me("UKPUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HKPPassw() As String
            Get
                Return CType(Me("HKPPassw"),String)
            End Get
            Set
                Me("HKPPassw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UKPPassw() As String
            Get
                Return CType(Me("UKPPassw"),String)
            End Get
            Set
                Me("UKPPassw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PKPPassw() As String
            Get
                Return CType(Me("PKPPassw"),String)
            End Get
            Set
                Me("PKPPassw") = value
            End Set
        End Property
        
        '''<summary>
        '''Titkosító kulcs útvonala
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Titkosító kulcs útvonala"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EncryptKeyPath() As String
            Get
                Return CType(Me("EncryptKeyPath"),String)
            End Get
            Set
                Me("EncryptKeyPath") = value
            End Set
        End Property
        
        '''<summary>
        '''Hova tegye a már elküldött küldeményeket (KR, CST, XML, ES3)
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Hova tegye a már elküldött küldeményeket (KR, CST, XML, ES3)"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaXMLmegnyitas() As String
            Get
                Return CType(Me("mappaXMLmegnyitas"),String)
            End Get
            Set
                Me("mappaXMLmegnyitas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaLefuzes() As String
            Get
                Return CType(Me("mappaLefuzes"),String)
            End Get
            Set
                Me("mappaLefuzes") = value
            End Set
        End Property
        
        '''<summary>
        '''Hova tegye a kitömörített állományokat? (KR, CST)
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Hova tegye a kitömörített állományokat? (KR, CST)"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaExtract() As String
            Get
                Return CType(Me("mappaExtract"),String)
            End Get
            Set
                Me("mappaExtract") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TorzsDBAutoImportCSVPath() As String
            Get
                Return CType(Me("TorzsDBAutoImportCSVPath"),String)
            End Get
            Set
                Me("TorzsDBAutoImportCSVPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TorzsDBAutoImportLastDate() As Date
            Get
                Return CType(Me("TorzsDBAutoImportLastDate"),Date)
            End Get
            Set
                Me("TorzsDBAutoImportLastDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Regisztrált() As Boolean
            Get
                Return CType(Me("Regisztrált"),Boolean)
            End Get
            Set
                Me("Regisztrált") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DbgFirstRun() As Boolean
            Get
                Return CType(Me("DbgFirstRun"),Boolean)
            End Get
            Set
                Me("DbgFirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AccessibleUserSettings() As String
            Get
                Return CType(Me("AccessibleUserSettings"),String)
            End Get
            Set
                Me("AccessibleUserSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property JavaDisabled() As Boolean
            Get
                Return CType(Me("JavaDisabled"),Boolean)
            End Get
            Set
                Me("JavaDisabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ErtesitNincsJava() As Boolean
            Get
                Return CType(Me("ErtesitNincsJava"),Boolean)
            End Get
            Set
                Me("ErtesitNincsJava") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ANYK_abevjavapath_cfg_Dir() As String
            Get
                Return CType(Me("ANYK_abevjavapath_cfg_Dir"),String)
            End Get
            Set
                Me("ANYK_abevjavapath_cfg_Dir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKadat() As String
            Get
                Return CType(Me("mappaANYKadat"),String)
            End Get
            Set
                Me("mappaANYKadat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKkuldendo() As String
            Get
                Return CType(Me("mappaANYKkuldendo"),String)
            End Get
            Set
                Me("mappaANYKkuldendo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKelkuldott() As String
            Get
                Return CType(Me("mappaANYKelkuldott"),String)
            End Get
            Set
                Me("mappaANYKelkuldott") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PkeyPassw() As String
            Get
                Return CType(Me("PkeyPassw"),String)
            End Get
            Set
                Me("PkeyPassw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DecryptKeyPath() As String
            Get
                Return CType(Me("DecryptKeyPath"),String)
            End Get
            Set
                Me("DecryptKeyPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ErtesitNincsPkey() As Boolean
            Get
                Return CType(Me("ErtesitNincsPkey"),Boolean)
            End Get
            Set
                Me("ErtesitNincsPkey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PasswPrinted() As Boolean
            Get
                Return CType(Me("PasswPrinted"),Boolean)
            End Get
            Set
                Me("PasswPrinted") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\TorzsAdatbazis.mdb")>  _
        Public ReadOnly Property TorzsadatokConnectionString() As String
            Get
                Return CType(Me("TorzsadatokConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=NyomtatvanyAdatok.mdb")>  _
        Public ReadOnly Property NyomtatvanyAdatokConnectionString() As String
            Get
                Return CType(Me("NyomtatvanyAdatokConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DefaultKitoltoID() As Integer
            Get
                Return CType(Me("DefaultKitoltoID"),Integer)
            End Get
            Set
                Me("DefaultKitoltoID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property mappaANYKmentesBackup() As String
            Get
                Return CType(Me("mappaANYKmentesBackup"),String)
            End Get
            Set
                Me("mappaANYKmentesBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property KeltezesHelye() As String
            Get
                Return CType(Me("KeltezesHelye"),String)
            End Get
            Set
                Me("KeltezesHelye") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UpgradeRequired() As Boolean
            Get
                Return CType(Me("UpgradeRequired"),Boolean)
            End Get
            Set
                Me("UpgradeRequired") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ZipFajlTorol() As Boolean
            Get
                Return CType(Me("ZipFajlTorol"),Boolean)
            End Get
            Set
                Me("ZipFajlTorol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AtvegyeANYKbolTitkositot() As String
            Get
                Return CType(Me("AtvegyeANYKbolTitkositot"),String)
            End Get
            Set
                Me("AtvegyeANYKbolTitkositot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ErtesitVanNyomtatvany() As Byte
            Get
                Return CType(Me("ErtesitVanNyomtatvany"),Byte)
            End Get
            Set
                Me("ErtesitVanNyomtatvany") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TDBDirectory() As String
            Get
                Return CType(Me("TDBDirectory"),String)
            End Get
            Set
                Me("TDBDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Edge")>  _
        Public Property BrowserPreferred() As String
            Get
                Return CType(Me("BrowserPreferred"),String)
            End Get
            Set
                Me("BrowserPreferred") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\eperhelper_data\eperelper_settings.xml")>  _
        Public Property ARCONSULTSettings() As String
            Get
                Return CType(Me("ARCONSULTSettings"),String)
            End Get
            Set
                Me("ARCONSULTSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("tucsi12")>  _
        Public Property ARCONSULTtitkjelszo() As String
            Get
                Return CType(Me("ARCONSULTtitkjelszo"),String)
            End Get
            Set
                Me("ARCONSULTtitkjelszo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ArchivTS() As Boolean
            Get
                Return CType(Me("ArchivTS"),Boolean)
            End Get
            Set
                Me("ArchivTS") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.homoki.eperhelper.My.MySettings
            Get
                Return Global.homoki.eperhelper.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
